# Generated by Django 5.2.16 on 2026-08-12 15:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABCClassificationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('abc_class', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('annual_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('run_date', models.DateField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abc_runs', to='master_data.item')),
            ],
        ),
        migrations.CreateModel(
            name='ForecastRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('MOVING_AVG', 'Moving Average'), ('EXP_SMOOTHING', 'Exponential Smoothing')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('forecasted_qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecast_runs', to='master_data.item')),
            ],
        ),
        migrations.CreateModel(
            name='ReorderRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_stock', models.IntegerField()),
                ('reorder_point', models.IntegerField()),
                ('recommended_qty', models.IntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACTIONED', 'Actioned'), ('DISMISSED', 'Dismissed')], default='OPEN', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('forecast_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recommendations', to='planning.forecastrun')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reorder_recommendations', to='master_data.item')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierKPI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.DateField()),
                ('otif_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('avg_lead_time', models.DecimalField(decimal_places=2, max_digits=5)),
                ('defect_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kpis', to='master_data.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierRiskScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_rating', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('contributing_factors', models.CharField(max_length=255)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_scores', to='master_data.supplier')),
            ],
        ),
    ]
