# Generated by Django 5.2.16 on 2026-08-12 12:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOMHeader',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('parent_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boms', to='master_data.item')),
            ],
        ),
        migrations.CreateModel(
            name='BOMLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qty_per_unit', models.DecimalField(decimal_places=4, max_digits=10)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='production.bomheader')),
                ('component_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_boms', to='master_data.item')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qty_planned', models.IntegerField()),
                ('state', models.CharField(choices=[('DRAFT', 'Draft'), ('RELEASED', 'Released'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20)),
                ('due_date', models.DateField()),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='production.bomheader')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qty_reserved', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='master_data.item')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='production.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qty_issued', models.IntegerField()),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='production.materialreservation')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='production.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='FGReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qty_completed', models.IntegerField()),
                ('completion_date', models.DateField()),
                ('work_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='fg_receipt', to='production.workorder')),
            ],
        ),
    ]
